site:
  title: CEDRIC
  favicon: /favicon.png
  description: Cedric 的个人主页，一个专注技术、乐于探索的代码爱好者！
  keywords: [个人主页, 博客, 技术, 生活, 前端开发, Vue, Nuxt, 开源]
  author: Cedric
  url: https://zxy6.indevs.in

# 首页首屏配置
hero:
  badgeText: 深度学习中
  descriptions:
    - 前景可待 · 未来可期
    - 业余 · 专注 · 享受生活
    - 一个专注技术、乐于探索的代码爱好者！
  skills:
    - C++
    - Vue.js
    - Nuxt.js
    - TypeScript
    - Go
    - Python
    - Git
    - Docker
    - Linux
  primaryAction:
    text: 个人博客
    url: https://blog.jyd.cc.cd
  primaryAction:
    text: 学习博客
    url: https://zxy6.indevs.in
  socialLinks:
    - name: GitHub
      url: https://github.com/wyx8999
      icon: ri-github-fill
    - name: Email
      url: mailto:zxy@zxy6.eu.cc
      icon: ri-mail-line
  rightPhoto:
    image: /photo.jpg
    iconA: ri-code-s-slash-line
    iconB: ri-palette-line
    iconC: ri-rocket-2-line

# 页脚配置
footer:
  startYear: 2026


# 文章配置
articles:
  blogUrl: https://zxy6.indevs.in
  #postAPI: https://api.talen.top/api/v1/articles
  # postRSS: https://blog.talen.top/rss.xml
  # postList:
  #   - title: 示例文章
  #     cover: /images/article-cover.jpg
  #     description: 文章简介
  #     category: 随笔
  #     time: 2026-04-09
  #     url: 
  postList:
    - title: 欢迎来到我的个人博客
      cover: /images/article-cover.jpg
      description: 记录学习、生活与技术分享，持续更新中～
      category: 随笔
      time: 2025-10-2

    - title: VuePress + FlecHome 主题搭建教程
      cover: /images/article-cover.jpg
      description: 从零开始搭建属于自己的静态博客网站，简单易上手
      category: 技术
      time: 2025-11-18

    - title: GitHub Pages 免费部署博客
      cover: /images/article-cover.jpg
      description: 无需服务器，5分钟把博客部署到互联网公开访问
      category: 部署
      time: 2026-2-22

# 网站配置
sites:
  - name: Cedric's World
    description: 记录学习，等你来探索
    url: https://zxy6.indevs.in
    icon: news-line
    tag: 博客
  - name: Cedric's blog
    description: 记录生活，等你来探索
    url: https://blog.jyd.cc.cd
    icon: news-line
    tag: 博客
  - name: Cedric导航
    description: 各种常用网站集合
    url: https://jyd.yuxian.xyz
    icon: news-line
    tag: 导航
  - name: Cedric's monitor
    description: 全面及时监测网站
    url: https://monitor.jyd.cc.cd
    icon: news-line
    tag: 监测

# 项目配置
projects:
  - wyx8999/blog
  - wyx8999/homepage
  - wyx8999/daily-bing

# 时间线配置
timeline:
  - date: 2026年3月
    title: 个人主页更名为「CEDRIC」
    description: 重构为 Nuxt，在原有风格基础上重新设计
    icon: ri-window-line
  - date: 2026年2月
    title: 博客平台更名为「Cedric」
    description: 完成了到【blog】项目的迁移和部署
    icon: ri-window-line
  - date: 2025年6月
    title: 【blog】项目完成规划
    description: 这是我第一个体系完整、接近产品级标准的项目
    icon: ri-code-box-line
  - date: 2025年5月
    title: 个人主页进行改版
    description: 切换到了 Astro，主题为 aria
    icon: ri-window-line
  - date: 2024年3月
    title: 个人主页正式成立
    description: 对 imsyy 主页项目进行了二开
    icon: ri-window-line
  - date: 2024年1月
    title: 博客平台正式成立
    description: 基于 Hexo 搭建了属于自己的个人博客
    icon: ri-window-line
  - date: 2020年
    title: 首次尝试文章创作
    description: 辗转于多个平台，内容质量低下，多为学习笔记类
    icon: ri-article-line
